name: Release

on:
  push:
    tags:
      - "v*"

env:
  GO_VERSION: "1.26.1"
  OUTPUT_BASE_NAME: "kopia-provisioner-${{ github.ref_name }}"

permissions:
  contents: write

jobs:
  license:
    name: Source Archives
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Set up Go tools
        run: go install github.com/google/go-licenses/v2@latest

      - name: Generate license files
        run: |
          go mod download
          go-licenses save ./... --save_path .build/${{ env.OUTPUT_BASE_NAME }}/kopia-provisioner --force
          cd tools/genversioninfo
          go mod download
          go-licenses save ./... --save_path ../../.build/${{ env.OUTPUT_BASE_NAME }}/tools/genversioninfo --force

      - name: Create tar.gz
        run: |
          cd .build
          tar -czf ${OUTPUT_BASE_NAME}-licenses.tar.gz ${OUTPUT_BASE_NAME}/

      - name: Create zip
        run: |
          cd .build
          zip -r ${OUTPUT_BASE_NAME}-licenses.zip ${OUTPUT_BASE_NAME}/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: licenses
          path: |
            .build/${{ env.OUTPUT_BASE_NAME }}-licenses.zip
            .build/${{ env.OUTPUT_BASE_NAME }}-licenses.tar.gz

  build:
    name: Build (${{ matrix.goos }}-${{ matrix.goarch }})
    needs: [license]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        goos: [linux, windows, darwin]
        goarch: [amd64, 386, arm64, arm]

        include:
          # Friendly names
          - goarch: amd64
            archname: x64
          - goarch: 386
            archname: x86
          # Windows extension
          - goos: windows
            goext: .exe
            archive: .zip
            
        exclude:
          # Windows does not support arm 32-bit
          - goos: windows
            goarch: arm
          # Darwin supports only 64-bit
          - goos: darwin
            goarch: 386
          - goos: darwin
            goarch: arm
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Compute target name
        run: |
          echo "TARGET_NAME=${{ env.OUTPUT_BASE_NAME }}-${{ matrix.goos }}-${{ matrix.archname || matrix.goarch }}" >> $GITHUB_ENV

      - name: Generate files
        run: go generate ./...

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          go build -o .build/artifacts/${{ env.OUTPUT_BASE_NAME }}/${TARGET_NAME}${{ matrix.goext }}

      - uses: actions/download-artifact@v4
        with:
          name: licenses
          path: .build/

      - name: Add licenses
        run: |
          cd .build
          unzip *-licenses.zip -d ./licenses
          mkdir -p artifacts/${{ env.OUTPUT_BASE_NAME }}/licenses
          mv ./licenses/*/* ./artifacts/${{ env.OUTPUT_BASE_NAME }}/licenses

      - name: Package artifacts
        if: ${{ matrix.archive == '.zip' }}
        run: |
          cd .build/artifacts
          zip -r ../${TARGET_NAME}.zip ./
      - name: Package artifacts
        if: ${{ matrix.archive != '.zip' }}
        run: |
          cd .build/artifacts
          tar -czf ../${TARGET_NAME}.tar.gz ${{ env.OUTPUT_BASE_NAME }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.goos }}-${{ matrix.goarch }}
          path: |
            .build/${{ env.TARGET_NAME }}.tar.gz
            .build/${{ env.TARGET_NAME }}.zip

  source:
    name: Source Archives
    needs: [license]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare sources
        run: |
          mkdir -p .build
          git archive --format tar --prefix=${{ env.OUTPUT_BASE_NAME }}/ -o .build/${{ env.OUTPUT_BASE_NAME }}-source.tar HEAD
          cd .build
          tar -xf ${{ env.OUTPUT_BASE_NAME }}-source.tar

      - uses: actions/download-artifact@v4
        with:
          name: licenses
          path: .build/

      - name: Add licenses
        run: |
          cd .build
          unzip *-licenses.zip -d ./licenses
          mkdir -p ${{ env.OUTPUT_BASE_NAME }}/licenses
          mv ./licenses/*/* ${{ env.OUTPUT_BASE_NAME }}/licenses

      - name: Create tar.gz
        run: |
          cd .build
          tar -cf ${{ env.OUTPUT_BASE_NAME }}-source.tar ${{ env.OUTPUT_BASE_NAME }}
          gzip ${{ env.OUTPUT_BASE_NAME }}-source.tar

      - name: Create zip
        run: |
          cd .build
          zip -r ${{ env.OUTPUT_BASE_NAME }}-source.zip ${{ env.OUTPUT_BASE_NAME }}

      - uses: actions/upload-artifact@v4
        with:
          name: source
          path: |
            .build/${{ env.OUTPUT_BASE_NAME }}-source.tar.gz
            .build/${{ env.OUTPUT_BASE_NAME }}-source.zip

  release:
    name: Create Release
    needs: [build, source, license]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Flatten artifact directory
        run: |
          cd artifacts
          find . -mindepth 2 -type f -print0 | xargs -0 -I{} mv "{}" .
          find . -mindepth 1 -type d -empty -delete

      - name: Generate SHA256SUMS
        run: |
          cd artifacts
          find . -type f -printf "%P\0" | sort -z | xargs -0 sha256sum > SHA256SUMS

      - name: Create GitHub Release
        if: ${{ !env.ACT }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: artifacts/**/*

      - name: Upload artifacts for ACT testing
        if: ${{ env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: act-release-artifacts
          path: artifacts/*
